version: '3.8'

services:

  mysql:
   image: mysql:8.0
   container_name: mysql_container
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: rrdb
   ports:
     - "3308:3306"
   networks:
     - spring_mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5


  spring-boot-app:
    build: .
    container_name: springbootapp
    depends_on:
      - mysql
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_container:3306/rrdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - spring_mysql

networks :
    spring_mysql:
      driver: bridge
